### ISSUE TITLE
Not the same signature as the builtin version

### ISSUE THREAD

**Issue by Neradoc** [adafruit/Adafruit_CircuitPython_Pixelbuf#7]
- **n** versus **size**
- keyword only arguments after that in the builtin version
- different type hints and default values for the header and trailer (not a big deal)

```py
class adafruit_pixelbuf.PixelBuf(n: int, byteorder: str = 'BGR', brightness: float = 1.0,
auto_write: bool = False, header: Optional[bytes] = None, trailer: Optional[bytes] = None):
```
```py
class adafruit_pixelbuf.PixelBuf(size: int, *, byteorder: str = 'BGR', brightness: float = 0,
auto_write: bool = False, header: circuitpython_typing.ReadableBuffer = b'', trailer: circuitpython_typing.ReadableBuffer = b''):
```
I think all the real-world uses work with both, giving the size as positional and the rest as keywords.
So I wonder if something should be done about that ?
(In addition the default brightness is wrong in the builtin docs but that's not an incompatibility).

**Comment by tekktrik** [comment]
I can look into this in a little while, assigning to myself so I don't forget
